version: "3.7"

services:
  chatgpt-for-chatbot-feishu:
    restart: always
    image: whatwewant/chatgpt-for-chatbot-feishu:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_PORT}:8080
    platform: linux/amd64
    environment:
      APP_ID: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_ID}
      APP_SECRET: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_SECRET}
      CHATGPT_API_KEY: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_CHATGPT_API_KEY}
      TUNNEL_ENABLE: "${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_ENABLE}"
      TUNNEL_TYPE: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_TYPE}
      TUNNEL_AUTH_TOKEN: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_AUTH_TOKEN}
      TUNNEL_SUBDOMAIN: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_SUBDOMAIN}
      OPENAI_MODEL: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_OPENAI_MODEL}
      FEISHU_BASE_URI: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_FEISHU_BASE_URI}
      
networks:
  default:
    external: true
    name: compose-ingress
