version: "3.7"

services:
  chatgpt-for-chatbot-feishu:
    restart: always
    image: whatwewant/chatgpt-for-chatbot-feishu:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_PORT}:8080
    environment:
      APP_ID: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_ID}
      APP_SECRET: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_SECRET}
      CHATGPT_API_KEY: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_CHATGPT_API_KEY}
      
networks:
  default:
    external: true
    name: compose-ingress
