version: "3.7"

services:
  chatgpt-for-chatbot-feishu:
    restart: always
    image: whatwewant/chatgpt-for-chatbot-feishu:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_PORT}:8080
    platform: linux/amd64
    environment:
      DEBUG: "${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_DEBUG}"
      GO_ZOOX_FETCH_DEBUG: "${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_DEBUG}"
      APP_ID: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_ID}
      APP_SECRET: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_APP_SECRET}
      OPENAI_API_KEY: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_OPENAI_API_KEY}
      API_PATH: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_API_PATH}
      TUNNEL_ENABLE: "${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_ENABLE}"
      TUNNEL_TYPE: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_TYPE}
      TUNNEL_AUTH_TOKEN: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_AUTH_TOKEN}
      TUNNEL_SUBDOMAIN: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_TUNNEL_SUBDOMAIN}
      OPENAI_MODEL: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_OPENAI_MODEL}
      FEISHU_BASE_URI: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_FEISHU_BASE_URI}
      CHATGPT_CONTEXT: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_CHATGPT_CONTEXT}
      CHATGPT_LANGUAGE: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_CHATGPT_LANGUAGE}
      OFFLINE_MESSAGE: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_OFFLINE_MESSAGE}
      ADMIN_EMAIL: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_ADMIN_EMAIL}
      BOT_NAME: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_BOT_NAME}
      # @DEPRECIATED CHATGPT_API_KEY, use OPENAI_API_KEY
      CHATGPT_API_KEY: ${SERVICE_CHATGPT_FOR_CHATBOT_FEISHU_CHATGPT_API_KEY}
      
networks:
  default:
    external: true
    name: compose-ingress
